# Chacune des valeurs ci-dessous sont celles de base du KamoofSMP

# Le nom des têtes
head-name: "§e%player%"
# La description des têtes
head-lore:
  - "§8Fais §lClick-Droit §8avec cette tête pour te déguiser en le joueur qu'elle représente"

# Les messages utilisent MiniMessages: https://docs.advntr.dev/minimessage/format
# Vous pouvez les prévisualiser avec le suite suivant: https://webui.advntr.dev/
messages:
  disguised: "<green>Tu es maintenant déguisé en <yellow>%player%"
  undisguise-info: "<click:run_command:/undisguise><yellow><bold>[CLIQUE ICI]</bold></click> <aqua>Pour Retirer ton déguisement ou fais la commande /undisguise"
  lostdisguise: "<red>Tu as perdu ton déguisement en mourrant (rip bozo)"
  nodisguise: "<red>Tu n'as actuellement aucun déguisement" # Si qql a le vrai msg, merci de me contacter
  undisguised: "<green>Tu as bien retiré ton déguisement"

# Je verrais si j'ajoute ça plus tard haha
# 1. Rename bug
# 2. Stack les items
# ptetre une option pour qu'ils ne soient pas stackable... idk
# cordialement, moi :3
options: