# Chacune des valeurs ci-dessous sont celles de base du KamoofSMP

# Le nom des têtes
head-name: "§e%player%"
# La description des têtes
head-lore:
  - "§8Fais §lClick-Droit §8avec cette tête pour te déguiser en le joueur qu'elle représente"

# Les messages utilisent MiniMessages: https://docs.advntr.dev/minimessage/format
# Vous pouvez les prévisualiser avec le suite suivant: https://webui.advntr.dev/
messages:
  disguised: "<green>Tu es maintenant déguisé en <yellow>%player%"
  undisguise-info: "<click:run_command:/undisguise><yellow><bold>[CLIQUE ICI]</bold> <aqua>Pour Retirer ton déguisement ou fais la commande /undisguise</click>"
  lostdisguise: "<red>Tu as perdu ton déguisement en mourrant (rip bozo)"
  nodisguise: "<red>Tu n'as pas de déguisement"
  undisguised: "<green>Tu as bien retiré ton déguisement"

options:
  # Si défini sur true, les têtes seront stackable, sur false, le cas contraire
  # Ceci n'affectera pas les têtes déjà créées
  stackable: false

  # Si défini sur true, le joueur se verra attribué le nom Game Profile également, contrairement à si défini sur false
  # Ceci permettra d'avoir également le pseudo volé lors de l'utilisation de commandes (tab complete, les commandes ne fonctionnent qu'avec le pseudo original)
  # Exemple: /msg vous proposera le pseudo nick, mais l'utiliser ne fonctionnera pas
  gameprofile: true

  restaure:
    # Si défini sur true, le déguisement est gardé à la reconnection, sur false, le cas contraire
    # Cette information est sauvegardée également quand le serveur redémarre ou est reload
    enabled: true
    # Si définis sur true, le joueur recevra les messages comme s'il venait de se déguiser, sur false, le contraire
    # Regardez la section "messages" au dessus pour + voir ces messages
    messages:
      disguised: false
      undisguise-info: false