name: KamoofSMP
description: Le KamoofSMP refait de 0
version: 1.0
depend: [ NickAPI]
main: me.ghosty.kamoofsmp.KamoofSMP
commands:
  givehead:
    description: Se donner la tête de n'importe quel joueur
    permission: kamoofsmp.give
  undisguise:
    description: Retirer sa fausse identité
    permission: kamoofsmp.undisguise
permissions:
  kamoofsmp.bypass:
    description: Ne pas faire dropper sa tête à la mort
    default: false
  kamoofsmp.undisguise:
    description: Retirer sa fausse identité
    default: true