name: KamoofSMP
version: 1.0.1
description: Le KamoofSMP refait de 0
author: Ghosty
api-version: 1.13
depend: [ NickAPI ]
main: me.ghosty.kamoofsmp.KamoofSMP
commands:
  givehead:
    description: Se donner la tête de n'importe quel joueur
    permission: kamoofsmp.give
  undisguise:
    description: Retirer sa fausse identité
#    permission: kamoofsmp.undisguise
# TODO: Vrai système où "ouais y'a une perm pour dire que c'est activé totalement, ouais.."